[env]
lattice_img_path='images/square_empty.png'
image_scale=10 #number of microns per pixel
sensor_model="update_sensor_reading_occupancy"
sensor_occ_radius = 120 #radius for the local occupancy grid sensor
n_agents=25
max_deposition_radius=1000 #max distance from the robot that it can deposit material
max_episode_length=1000
motion_model='unrestricted' #'unrestricted' or 'restricted' -- unrestricted means robots can travel through material
                            # restricted means they cannot

[rule]
rule_file = "blob_rule"
rule_name = "BlobRule"
include_env = true


[rule_args.blob_kwargs]



